language: go

go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - tip


before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpcap-dev
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
